### DISCUSSION TITLE
通过 Slack 接口+Message pusher 服务实现主流推送渠道全部接入

### DISCUSSION THREAD

**Discussion by zj1123581321** [opennaslab/kubespider#551] [Show and tell]
https://github.com/songquanpeng/message-pusher 是一个推送项目。
- 支持多种推送方式+聚合
- 可以自定义 webhook 地址，反向适配各种平台。

基于这个项目，可以在 Kubespider 里配置 slack 地址，通过 Message-pusher 项目实现主流平台全部接入。

# 配置文件：
```
slack:
  type: slack_notification_provider
  enable: true
  host: xxx
  channel: channel_name
  username: bot_name
  title_emoji: none
```

# 接口配置：
## 提取规则
```
{
  "title": "text",
  "description": "blocks.1.text.text",
  "url": "url"
}
```
## 构建规则
```
{
  "title": "$title",
  "description": "$description",
  "url": "$url"
}
```

![image](https://github.com/user-attachments/assets/be9be342-021e-4dff-8330-a4066664c761)
