### ISSUE TITLE
配置文件修改了不生效

### ISSUE THREAD

**Issue by SaulJWu** [opennaslab/kubespider#271]
通过修改`download_provider.yaml`

```yaml
aria2:
  type: aria2_download_provider
  enable: false
  download_base_path: "/downloads/"
  rpc_endpoint_host: http://127.0.0.1
  rpc_endpoint_port: 6800
  secret: kubespider
  priority: 3
qbittorrent:
  type: qbittorrent_download_provider
  enable: true
  download_base_path: "/downloads/"
  http_endpoint_host: http://127.0.0.1
  http_endpoint_port: 8080
  username: admin
  password: adminadmin
  verify_webui_certificate: false
  priority: 0
  tags:
    - kubespider
```
但是自己测试，还是不行，手动添加任务到qbittorrent可以。
然后访问
`http://192.168.0.111:3080/api/v1/downloadproviders`

回复：
```json
{
    "aria2": true,
    "qbittorrent": false,
    "transmission": false,
    "xunlei": false,
    "youget": false,
    "yt-dlp": false
}
```
