### ISSUE TITLE
自动下载B站博主更新的视频出错

### ISSUE THREAD

**Issue by Znonymous29** [opennaslab/kubespider#450]
## Describe the bug

无法使用yutto自动下载B站博主更新，报错 ` BilibiliVloggerSubscribeSourceProvider get links error:'list' `
![image](https://github.com/opennaslab/kubespider/assets/19743142/bbba091c-5dd0-4064-8e13-8ed90763f9c1)

## Describe the running environment

yutto功能使用正常，可以利用kubespider插件在B站下载视频。使用docker compose进行部署使用
```yaml
version: "3"

services:
  kubespider:
    container_name: kubespider
    image: cesign/kubespider:latest
    depends_on:
      - aria2-pro
      - yutto-downloader
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    ports:
      - 3080:3080
    volumes:
      - /docker/kubespider/config:/app/.config
    restart: unless-stopped
  aria2-pro:
    container_name: aria2-pro
    image: cesign/aria2-pro:latest
    logging:
        options:
            max-size: 1m
    ports:
        - 6800:6800
        - 6888:6888
    environment:
        - PUID=1000
        - PGID=100
        - RPC_SECRET=kubespider
        - RPC_PORT=6800
        - LISTEN_PORT=6888
    volumes:
        - /docker/kubespider/aria2:/config
        - /aria2:/downloads
    network_mode: host
    restart: unless-stopped
  yutto-downloader:
    container_name: yutto-downloader
    image: cesign/yutto-downloader:latest
    environment:
        - PUID=1000
        - PGID=100
        - BILIBILI_SESSDATA=XXXXXX
    volumes:
        - /docker/kubespider/yutto:/app/config
        - /yutto:/app/downloads
    network_mode: host
    restart: unless-stopped
```
